-- CreateTable
CREATE TABLE "Game" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "homeId" INTEGER NOT NULL,
    "awayId" INTEGER NOT NULL,
    "start" DATETIME NOT NULL,
    "winnerId" TEXT NOT NULL,
    "league" TEXT NOT NULL,
    "week" TEXT NOT NULL,
    "season" TEXT NOT NULL,

    FOREIGN KEY ("homeId") REFERENCES "Team"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY ("awayId") REFERENCES "Team"("id") ON DELETE CASCADE ON UPDATE CASCADE
);
